# NumPy Tutorial

# Learn NumPy

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5,6,7,8])

print(arr)

print(type(arr))


[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


# NumPy Introduction

# What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

# Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

# Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

Where is the NumPy Codebase?
The source code for NumPy is located at this github repository https://github.com/numpy/numpy

# NumPy Creating Arrays

# Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


# Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [4]:
import numpy as np

arr = np.array(42)

print(arr)


42


# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# NumPy Array Indexing

# Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


# Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [10]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


# Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [12]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


# Negative Indexing
Use negative indexing to access an array from the end.

In [13]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# NumPy Array Slicing

# Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# Negative Slicing
Use the minus operator to refer to an index from the end:

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# STEP
Use the step value to determine the step of the slicing:

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


[1 3 5 7]


# Slicing 2-D Arrays

In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [21]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])


[3 8]


In [22]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Array Shape

# Shape of an Array
The shape of an array is the number of elements in each dimension.

Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# What does the shape tuple represent?
Integers at every index tells about the number of elements the corresponding dimension has.

In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

# NumPy Array Reshaping

# Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

# Reshape From 1-D to 2-D

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

# Returns Copy or View?

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


# Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [30]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


# Random Numbers in NumPy

# What is a Random Number?
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.

Generate Random Number
NumPy offers the random module to work with random numbers.

In [31]:
from numpy import random

x = random.randint(100)

print(x)

14


# Generate Random Float
The random module's rand() method returns a random float between 0 and 1.

In [32]:
from numpy import random

x = random.rand()

print(x)

0.7157848371200348


# Generate Random Array
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

Integers
The randint() method takes a size parameter where you can specify the shape of an array.

In [33]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[69 13 87 75 61]


In [34]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)


[[36 31 86 56 58]
 [56 51 69 79 55]
 [61 87 27 53 15]]


# Floats
The rand() method also allows you to specify the shape of the array.

In [35]:
from numpy import random

x = random.rand(5)

print(x)

[0.14442286 0.25646326 0.11721078 0.46701557 0.54258008]


In [36]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.61002875 0.27426285 0.58545507 0.57704473 0.42611812]
 [0.20542373 0.6355074  0.24573581 0.96861877 0.62657034]
 [0.63765602 0.4310805  0.90900775 0.01962987 0.02949039]]


# Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [37]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

3


In [38]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 5 9 5 7]
 [5 9 7 7 5]
 [7 9 5 5 5]]


# Aggregate functions in numpy:¶

In [1]:
import numpy as np
data=np.array([10,20,30,40,50,60,70,80])
total=np.sum(data)
average=np.mean(data)
minimum=np.min(data)
maximum=np.max(data)
std_dev=np.std(data)
print("data:",data)
print("sum:",total)
print("mean:",average)
print("min:",minimum)
print("max:",maximum)
print("std:",std_dev)

data: [10 20 30 40 50 60 70 80]
sum: 360
mean: 45.0
min: 10
max: 80
std: 22.9128784747792


# vectarization:

In [1]:
import numpy as np
arr1=np.array([10,20,30,40,50])
arr2=np.array([60,70,80,90,100])
print(arr1.size)
print(arr1,arr2)
a=arr1+arr2
print(a)
b=arr1.sum()
print(b)
print(arr2.sum())
c=arr1.mean()
print(c)
print(arr2.mean())
print(arr2.max())
print(arr1.min())
d=arr1*arr2
print(d)
print(arr1/arr2)

5
[10 20 30 40 50] [ 60  70  80  90 100]
[ 70  90 110 130 150]
150
400
30.0
80.0
100
10
[ 600 1400 2400 3600 5000]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [2]:
result=lambda a,b:a+b
result(5,6)

9

In [3]:
def square(a):
    return a**2
l1=[1,2,3,4]
list1=list(map(square,l1))
list1

[1, 4, 9, 16]

In [4]:
result=lambda a,b:a*b
result(2,4)

8

In [5]:
result=lambda a,b:a-b
result(10,4)

6

In [6]:
result=lambda a:a**2
result(3)


9

In [7]:
def even(x):
    if x%2==0:
        return True
l1=[1,2,3,4,5]
even=list(filter(even,l1))
even

[2, 4]

In [8]:
l1=[1,2,3,4,5]
even=list(filter(lambda x: x > 2, l1))
even

[3, 4, 5]

In [9]:
l1=[1,2,3,4,5]
even=list(filter(lambda x: x < 2, l1))
even

[1]

In [10]:
from functools import reduce
def mean(x,y):
    return x+y/4
l1=[20,30,40,50,60]
result=reduce(mean,l1)
result

65.0

In [11]:
from functools import reduce
def max(x,y):
    return x+y/2
l1=[20,30,40,50,60]
result=reduce(max,l1)
result

110.0

In [12]:
from functools import reduce
def min(x,y):
    return x+y/2
l1=[10,20,30,40,50]
result=reduce(min,l1)
result

80.0